[[plugins]]
package = "@netlify/angular-runtime"
[plugins.inputs]
disable_ssr = true
# This extra flag can sometimes help bypass the auto-detection
handle_browser_only = true

[build]
command = "ng build"
publish = "dist/auralicode"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
