[[plugins]]
package = "@netlify/angular-runtime"
[plugins.inputs]
disable_ssr = true

[build]
command = "npm run build"
publish = "dist/auralicode/browser"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
